name: Setup
description: Setup CI environment with cache

runs:
  using: composite
  steps:
    - name: 🟡 Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-
    - name: 🟢 Setup Bun
      uses: oven-sh/setup-bun@v2
    - name: ⚙️ Install dependencies
      shell: bash
      run: bun install
